apiVersion: v1
kind: Service
metadata:
  name: redis-svc              # 必须和 ConfigMap 中的 REDIS_HOST 一致
spec:
  type: ClusterIP              # ⚠️ 关键要求：类型为 ClusterIP，仅内部可达
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis